### ISSUE TITLE
Would you please explain this workaround?

### ISSUE THREAD

**Issue by ackelcn** [dmalhotra/SCTL#3]
I am working on the test cases of clang. I just find that you encounter a bug of clang. This commit is https://github.com/dmalhotra/SCTL/commit/fc3f7e72f3333cdc90c4eb5b5ef3cf3fb8077dde. 

Would you please explain the problem? Would you please reduce the code? I will submit the problem to clang, so that this problem can be fixed.

**Comment by dmalhotra** [comment]
It is not a bug. It seems other compilers don't mind if you interchange struct and class in forward declaration, but clang seems more strict so I had to change "class Kernel;" to "struct Kernel;" in fmm-wrapper.hpp

Could you explain the issue you are facing?
